### ISSUE TITLE
GPO link service for CFR parts that aren't numbers

### ISSUE THREAD

**Issue by peregrinator** [usgpo/link-service#1]
We’re using the GPO link service to link users to the correct PDF for a CFR part but are running into an error with 15 CFR 4a.

This url returns an error: https://api.fdsys.gov/link?collection=cfr&link-type=pdf&partnum=4a&titlenum=15&year=…

Part 4 works:
This url returns an error: https://api.fdsys.gov/link?collection=cfr&link-type=pdf&partnum=4&titlenum=15&year=m…

But the agency also has added a Part 4a that is a different part from Part 4. It looks like the PDF for Part 4 has some of Part 4a at the end because of the 3-column layout in the print (but is incomplete - it ends at 4a.3). 

See:
https://www.gpo.gov/fdsys/pkg/CFR-2017-title15-vol1/pdf/CFR-2017-title15-vol1-part4.pdf#page=36
Vs:
https://www.gpo.gov/fdsys/pkg/CFR-2017-title15-vol1/pdf/CFR-2017-title15-vol1-subtitleA.pdf#page=54

Thanks!

**Comment by jonquandt** [comment]
@peregrinator -- looking into this now. I'm going to see if it's just a configuration change that we can get into the upcoming release or if there's additional work needed.

**Comment by jonquandt** [comment]
@peregrinator -- this is something that we need to make a fix for, but it's too late for our current release. We'll plan for it in our next release.

**Comment by jonquandt** [comment]
@peregrinator - we've updated the govinfo link service to support this use case.

https://www.govinfo.gov/link/cfr/15/4a?link-type=pdf

https://www.govinfo.gov/link-docs

**Comment by jonquandt** [comment]
@peregrinator -- ok to close from your perspective?
