### ISSUE TITLE
U.S.C. 50

### ISSUE THREAD

**Issue by UnitedStatesofamerica23** [usgpo/link-service#19]

**Comment by jonb665** [comment]
No one assigned

> need help

**Comment by jonquandt** [comment]
@UnitedStatesofamerica23 or @jonb665  -- can you provide details of what the issue is? There is currently no description in the original request.

**Comment by jonb665** [comment]
Not really sure but a little help on where to begin would be great @UnitedStatesofamerica23

**Comment by jonquandt** [comment]
Closing due to no additional feedback from original requester.
