### ISSUE TITLE
EU PEDRO MORAIS, ESTOU COM UMA DÚVIDA.

### ISSUE THREAD

**Issue by ASSIAPLI** [usgpo/link-service#25]
A minha dúvida é; IRS.com prioriza dados de organização não governamentais para não pagar imposto? E como faço pra abrir filial no Brasil para atender o público brasileiro.

I PEDRO MORAIS, I HAVE A DOUBT.

My question is; Does IRS.com prioritize non-governmental organization data to avoid paying tax? And how do I open a branch in Brazil to serve the Brazilian públic

https://github.com/ASSIAPLI/explore/pull/1

**Comment by llaplant** [comment]
Closing. Out of scope for the link-service repository.
