### ISSUE TITLE
Getting “section exceeds allowed max length” for certain 42 USC links

### ISSUE THREAD

**Issue by brittag** [usgpo/link-service#30]
As part of a Medicaid & CHIP web application project, my team is generating clickable links for USC sections in a few titles of 42 USC Chapter 7. This link service is very helpful, and we appreciate it.

I would expect the following link-service links to work because they include valid section numbers - compare with [USC Chapter 7 table of contents on house.gov](https://uscode.house.gov/view.xhtml?hl=false&edition=prelim&req=granuleid%3AUSC-prelim-title42-chapter7-front&num=0&saved=%7CZ3JhbnVsZWlkOlVTQy1wcmVsaW0tdGl0bGU0Mi1jaGFwdGVyNy1mcm9udA%3D%3D%7C%7C%7C0%7Cfalse%7Cprelim).

But when I click these links, I get an error page that says **"Search criteria failed validation: section exceeds allowed max length"**.

I spot-checked a few of the annual edition PDFs to make sure they really exist - for example, [here's 42 USC 1395aaa–1](https://www.govinfo.gov/content/pkg/USCODE-2021-title42/pdf/USCODE-2021-title42-chap7-subchapXVIII-partE-sec1395aaa-1.pdf) and [42 USC 1395w–27a](https://www.govinfo.gov/content/pkg/USCODE-2021-title42/pdf/USCODE-2021-title42-chap7-subchapXVIII-partC-sec1395w-27a.pdf). Seems like the link service just can't currently retrieve them due to the extra-long section numbers.

I'd love to know if a fix on your end would be feasible, and what the timeline might be. Thank you!

- https://www.govinfo.gov/link/uscode/42/1395aaa-1
- https://www.govinfo.gov/link/uscode/42/1395w-101
- https://www.govinfo.gov/link/uscode/42/1395w-102
- https://www.govinfo.gov/link/uscode/42/1395w-103
- https://www.govinfo.gov/link/uscode/42/1395w-104
- https://www.govinfo.gov/link/uscode/42/1395w-111
- https://www.govinfo.gov/link/uscode/42/1395w-112
- https://www.govinfo.gov/link/uscode/42/1395w-113
- https://www.govinfo.gov/link/uscode/42/1395w-114
- https://www.govinfo.gov/link/uscode/42/1395w-114a
- https://www.govinfo.gov/link/uscode/42/1395w-114b
- https://www.govinfo.gov/link/uscode/42/1395w-114c
- https://www.govinfo.gov/link/uscode/42/1395w-114d
- https://www.govinfo.gov/link/uscode/42/1395w-115
- https://www.govinfo.gov/link/uscode/42/1395w-116
- https://www.govinfo.gov/link/uscode/42/1395w-131
- https://www.govinfo.gov/link/uscode/42/1395w-132
- https://www.govinfo.gov/link/uscode/42/1395w-133
- https://www.govinfo.gov/link/uscode/42/1395w-134
- https://www.govinfo.gov/link/uscode/42/1395w-141
- https://www.govinfo.gov/link/uscode/42/1395w-151
- https://www.govinfo.gov/link/uscode/42/1395w-152
- https://www.govinfo.gov/link/uscode/42/1395w-153
- https://www.govinfo.gov/link/uscode/42/1395w-27a

**Comment by jonquandt** [comment]
Thank you for pointing this out. We will review with the team and report back on the expected time for resolution.

**Comment by jonquandt** [comment]
Good afternoon - we have made a fix for this issue, so most of the links above should now be working. 

I'm not seeing the following in GovInfo currently:
1395w-114b
1395w-114c
1395w-114d

Looking at [subpart 2](https://www.govinfo.gov/app/details/USCODE-2021-title42/USCODE-2021-title42-chap7-subchapXVIII-partD-subpart2) (which should contain these, if they exist), I don't see a mention of those within the [pdf](https://www.govinfo.gov/content/pkg/USCODE-2021-title42/pdf/USCODE-2021-title42-chap7-subchapXVIII-partD-subpart2.pdf) or [text](https://www.govinfo.gov/content/pkg/USCODE-2021-title42/html/USCODE-2021-title42-chap7-subchapXVIII-partD-subpart2.htm), either in headings or references elsewhere within the file.

Could you verify that those are expected?

**Comment by brittag** [comment]
Ah yeah, good point, according to the House US Code site, those three sections were added in August 2022 ([1395w-114b](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section1395w-114b&num=0&edition=prelim); [1395w-114c](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section1395w-114c&num=0&edition=prelim); [1395w-114d](https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title42-section1395w-114d&num=0&edition=prelim)). It makes sense that the link service can't find them - they're not in the 2021 annual edition.

Thank you so much for fixing this pattern!

**Comment by jonquandt** [comment]
Of course - thank you for identifying the issue!
